### PR TITLE
Added obsidian and redstone gens

### PR DESCRIPTION
**Pull request by FN-FAL113**
Some additions to SMG :)

### CODE REVIEW

**Review by variananora — APPROVED** [review]
I think the recipe can be a little bit more expensive, but otherwise LGTM

**Comment by Sefiraat** [comment]
I'd actually agree with Var and say for anything genning more complex materials (in this case specifically the obsidian) it would be good to add an intermediary craft to make it both more costly and somewhat more of a mission to craft it. Perhaps in the broken version we can add something from slimefun that represents breaking power, one of the pickaxe perhaps?

**Comment by FN-FAL113** [comment]
can add those sf pickaxe to broken ones, should it be added for obsi only or both

**Comment by Sefiraat** [comment]
I think just the obsidian, Redstone is fairly easy to get in bulk mining, quicker in most cases than a ticking machine - but obby? Not so much - that's my view at least though im open to w/e fits :)

**Comment by FN-FAL113** [comment]
Thoughts/suggestions are open for the new recipe I added :)

**Comment by variananora** [comment]
To be honest with you it is kinda weird for me to use "Iron Pickaxe" on obsidian, but after checking Slimefun's pickaxe it doesn't make sense to use other ones.... Waiting for Sefi to response then.

**Comment by FN-FAL113** [comment]
Its "Cobalt Pickaxe" though if we were to respect its material in terms of slimefun and its enchanted too ig but it is subject to change though :)

**Comment by Sefiraat** [comment]
@FN-FAL113 Can you confirm you've tested this all in-game? If so I can merge otherwise it'll need to await tomorrow when I have some spare time.

As for the recipe, seems ok to me - 4 cobalt pickaxes for the broken ones which you then 'fix' seems ok to me.

**Comment by FN-FAL113** [comment]
Tested it beforre this pr was made, in game. Crafting and the Tick rate were tested :)

**Review by Sefiraat — APPROVED** [review]

**Comment by Sefiraat** [comment]
Thanks for this, ill add the config settings later when I get home :)

**Pull request merged**
